### ISSUE TITLE
Error when using SelectMultipleField styled as checkboxes

### ISSUE THREAD

**Issue by markosski** [fuhrysteve/wtforms-parsleyjs#4]
I'm using multi-checkbox form element following solution from http://wtforms.simplecodes.com/docs/1.0.1/specific_problems.html (bottom of the page)
I'm getting this error:
`File ".../python3.4/site-packages/wtformsparsleyjs/core.py", line 292, in __init__
    super(SelectMultipleField, self).__init__(widget=Select(multiple=True), *args, **kwargs)
TypeError: __init__() got multiple values for keyword argument 'widget'`

I don't quite understand why there is a need to overwrite default widgets from parent classes?

**Comment by SmileyJames2** [comment]
The documentation linked is for WTForms 1.0.1, this fork is from ParsleyJS 2 and WTForms 2. However I believe it would still be possible to make a "multi-checkbox".

In WTForms BooleanField is a checkbox field, can you just use many BooleanFields?

**Comment by markosski** [comment]
@SmileyJames Nope this will not do either. Seems like the problem is that each class that extends wtform field already sets the widget (the one with mixin). That solution I found passes different 'widget' to override default one but since it is already set explicitly in constructor it raises exception. I will try couple ideas and let you know.

**Comment by fuhrysteve** [comment]
How about something like this?

``` python
class SelectMultipleField(_SelectMultipleField):
    def __init__(self, *args, **kwargs):
        super(SelectMultipleField, self).__init__(
            widget=kwargs.get('widget', Select(multiple=True)), *args, **kwargs)


```

**Comment by markosski** [comment]
Looks nice, my idea was to set class level variable `widget = Select(multiple=True)` and remove widget argument from constructor completely.

**Comment by fuhrysteve** [comment]
Good call - it looks like that's exactly how wtforms does this internally:

https://github.com/wtforms/wtforms/blob/master/wtforms/fields/html5.py#L67

**Comment by fuhrysteve** [comment]
This should be resolved now, right?

**Comment by markosski** [comment]
Yes, it's good now.
